### ISSUE TITLE
ValueError: zero-size array to reduction operation minimum which has no identity

### ISSUE THREAD

**Issue by nimesh131** [NotTrueFalse/Captcha_solving#3]
When try to process images (.png) getting the error as - 

```
Traceback (most recent call last):
  File "D:\xampp\htdocs\testing\preyash\PyCaptcha\Captcha_solving-main\process_images.py", line 10, in <module>
    result = preprocess_image('temp/'+img)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\xampp\htdocs\testing\preyash\PyCaptcha\Captcha_solving-main\pre_processing.py", line 39, in preprocess_image
    result = result[x.min():x.max(), y.min():y.max()]
                    ^^^^^^^
  File "D:\Python\Lib\site-packages\numpy\core\_methods.py", line 45, in _amin
    return umr_minimum(a, axis, None, out, keepdims, initial, where)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
ValueError: zero-size array to reduction operation minimum which has no identity
```
Unable to figure out to fix the error.

**Comment by NotTrueFalse** [comment]
Hello, can you show me your file structure under `Captcha_solving-main`? (using the command tree)
